RENDER=prman
# FILE=mandarin
# FILE=image1
FILE=image2
SLCOMPILER=oslc
VIEWER=sho
SLEXT=oso

SHADERNAME_COLOR=first
SHADERNAME_DISP=displacement_shader
SHADERNAME_TABLE=table

all : ${FILE}.tiff
	${VIEWER} ${FILE}.tiff

${SHADERNAME_COLOR}.${SLEXT} : ${SHADERNAME_COLOR}.osl
	${SLCOMPILER} ${SHADERNAME_COLOR}.osl

${SHADERNAME_DISP}.${SLEXT} : ${SHADERNAME_DISP}.osl
	${SLCOMPILER} ${SHADERNAME_DISP}.osl

${SHADERNAME_TABLE}.${SLEXT} : ${SHADERNAME_TABLE}.osl
	${SLCOMPILER} ${SHADERNAME_TABLE}.osl

${FILE}.tiff : ${SHADERNAME_DISP}.${SLEXT} ${SHADERNAME_COLOR}.${SLEXT} ${SHADERNAME_TABLE}.${SLEXT} ${FILE}.rib
	cat ${FILE}.rib | ${RENDER}

# doesnt work lol
clean :
	rm -f *.oso